 import Head from 'next/head';
 import {BsFillMoonStarsFill} from 'react-icons/bs';
 import {AiFillTwitterCircle,
         AiFillLinkedin,
         AiFillYoutube,} from 'react-icons/ai';
 import Image from "next/image";
 import deved from "../public/dev-ed-wave.png";
 import { useState } from "react";
 import Link from 'next/link';

export default function Home() {
  const [darkMode,setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>DEVIREDDY VISHNU VAIBHAV REDDY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className= "bg-slate-200 px-10 md:px-20 lg:px-40 dark:bg-gray-800 ">
          <section className="min-h-screen">
            <nav className="py-8 mb-12 flex justify-between">
            <h1 className="text-lg font-burtons bg-gradient-to-l from-cyan-500 to-blue-400 px-4 py-2 rounded-md ml-8 text-neutral-700">reddtactt</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
              <li><Link href="/resume" className= "bg-gradient-to-r from-cyan-500 to-blue-400 px-4 py-2 rounded-md ml-8 font-burtons text-neutral-700">Resume</Link></li>
            </ul>
            </nav>
            
            <div className="text-center">
              <h1 className="text-2xl font-extrabold text-blue-500">DEVIREDDY VISHNU VAIBHAV REDDY</h1>
              <h3 className="text-xl font-semibold text-purple-500">AT VIT-AP..</h3>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-cyan-500 to-white rounded-full w-44 h-40 mt-5 overflow-hidden border-dashed">
              <Image src={deved} width={300} height={300} alt={''} />
            </div>
            <div className="text-center py-4">
            <h2 className="text-lg font-burtons text-teal-800">current position....</h2>
            <p className="text-lg font-burtons text-teal-900">Till today my heart is filled with a cutie friend.... Now i broke up with her... So Now I am getting coding programs into my heart.. Hope it will fill up soon.</p>
            </div>
            <div className="py-0.5 text-5xl flex justify-center gap-10 px-10">
              <a href='https://www.youtube.com/watch?v=o05ZP6_JQqE'><AiFillTwitterCircle className="text-cyan-500"/></a>
              <AiFillLinkedin className="text-blue-700"/>
              <AiFillYoutube className="text-red-600"/>
            </div>
          </section>
      </main>
  </div>
  );
}


